spring.application.name=ads-manager
spring.security.oauth2.client.registration.facebook.client-id=983939736689583
spring.security.oauth2.client.registration.facebook.client-secret=EAANZB41J8W68BOxC5JBlSfZAXTf2v5BSfO5JDDxdqwExZCp48XCkg0DAPcHrZABcCd6WMYZBjZB6BZBtezaZBb34RZBwzgBFlPo5pBEnvk6JI5GDMTzZAFKIneATs43TmcjgCTeEGSb473k7fMjfZBAVyZCiLpTFufiXCBaWCTI4li1WGvWRUAM5xyzkFO50Kqryz59vjo1XdgdDpshryMks4YmvpOX6ydXEzvPZCVlV4DLaRZCaBJmyChUBYZD
#spring.security.oauth2.client.registration.facebook.client-secret=EAAQAjqEmHbQBO8ZCp5yFv3AniV6CEKBh5aMiNMJqZBnf7AaHVVliUDdv6huRECNZBbaQslQidwj0ErdWvDVcsNuHdLTKKyA8tOB4C1nyGVH3SJZC619ZC20ZC7MLtcBeJznv660Q2UgbF7sqvZCZAVgf33G3i6lPN2smWSAHCIZAZBc0VKvKK8DtOxhkCfLtFMmdEDih4V3akjI9w9nG1nyMX3hUqycyrGRtH014iW
spring.security.oauth2.client.registration.facebook.scope=email,catalog_management,pages_show_list,ads_management,business_management,pages_read_engagement,pages_manage_ads
spring.security.oauth2.client.registration.facebook.redirect-uri="http://localhost:8080/oauth2/callback/facebook"
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v22.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v22.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email

# PostgreSQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/whilter
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings (optional, for Spring Data JPA)
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
